run:
  timeout: 10m
  tests: true
  build-tags: []
  go: "1.24"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    # Exclude specific error checks in test files
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*os.File).Close

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # Exclude SA1019 deprecation warnings for jobs.Manager migration (in progress)
    - linters:
        - staticcheck
      text: "SA1019.*jobs\\.Manager|SA1019.*jobs\\.NewManager|SA1019.*pkg/jobs"
    # Exclude all errcheck in test files
    - path: _test\.go
      linters:
        - errcheck

    # Exclude errcheck for deferred cleanup in all files
    - linters:
        - errcheck
      text: "Error return value of .*(Cleanup|Stop)"

    # Exclude errcheck for job manager updates (fire and forget pattern)
    - linters:
        - errcheck
      text: "Error return value of `.*jobManager.Update`"

    # Exclude errcheck for context manager cleanup in agents
    - path: pkg/agents/
      linters:
        - errcheck
      text: "Error return value of `contextMgr.Cleanup`"

    # Exclude errcheck for process kill (best effort)
    - linters:
        - errcheck
      text: "Error return value of `.*Process.Kill`"

    # Exclude errcheck for flag parsing (exits on error)
    - linters:
        - errcheck
      text: "Error return value of `.*Parse`"

    # Exclude errcheck for HTTP response writes (already handled by HTTP stack)
    - path: pkg/httpbridge/
      linters:
        - errcheck
      text: "Error return value of `.*Write`"

    # Exclude errcheck for JSON encoding in HTTP handlers (already handled)
    - path: pkg/httpbridge/
      linters:
        - errcheck
      text: "Error return value of `.*Encode`"

    # Exclude errcheck for voice client multipart writes (best effort)
    - path: pkg/voice/
      linters:
        - errcheck
      text: "Error return value of `.*WriteField`"

    # Exclude errcheck for best-effort JSON operations
    - linters:
        - errcheck
      text: "Error return value of `.*Unmarshal`"

    # Exclude errcheck for token encoding in calendar server
    - path: cmd/calendar-mcp-server/
      linters:
        - errcheck
      text: "Error return value of `.*Encode`"

    # Exclude errcheck for navigate tree building (best effort)
    - path: pkg/tools/navigate\.go
      linters:
        - errcheck
      text: "Error return value of `.*buildTree`"

    # Exclude gosimple for string prefix checks
    - linters:
        - gosimple
      text: "S1017.*TrimPrefix"

    # Exclude staticcheck nil check warnings in repos executor
    - path: pkg/repos/executor\.go
      linters:
        - staticcheck
      text: "SA4031"

    # Exclude unused for intentionally unused test helpers
    - path: pkg/agents/
      linters:
        - unused
      text: "(buildSystemPrompt|executeInference|parseReview|extractIssueCount|postReviewToGitHub|getPRNumber|getSystemPrompt)"

    # Exclude unused for CI parser (future use)
    - path: pkg/hooks/ci_parser\.go
      linters:
        - unused
      text: "type `gitlabCI`"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
